name: Build and Release

on:
  push:
    branches: [ main ]

permissions:
  id-token: write
  attestations: write

jobs:
  build-and-release:
    permissions: write-all
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4.2.2

    - run: |
        mkdir cosmocc
        cd cosmocc
        wget https://cosmo.zip/pub/cosmocc/cosmocc.zip
        unzip cosmocc.zip

    - run: cosmocc/bin/cosmocc -o bazel main.c

    - uses: actions/attest-build-provenance@v2.3.0
      with:
        subject-path: ./bazel

    #- run: gh release view --json tagName --jq .tagName | { read version; echo "RELEASE_TAG=v$((${version#v} + 1))"; } >> $GITHUB_ENV
    - run: echo "RELEASE_TAG=v0" >> $GITHUB_ENV
    - run: gh release create ${{ env.RELEASE_TAG }} --generate-notes
      env:
           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: gh release upload ${{ env.RELEASE_TAG }} ./bazel
      env:
           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
